"""
This file is part of immanuel - (C) The Rift Lab
Author: Robert Davies (robert@theriftlab.com)


This module calculates aspects between chart objects based on
the settings provided by the Config class.

The functions also rely on the object data generated by the sweph module.

"""

import swisseph as swe

from immanuel.const import calc
from immanuel.settings import DEFAULTS, Config
from immanuel.tools import position


def between(object1: dict, object2: dict, config: Config = DEFAULTS) -> dict:
    """Returns any aspect between the two passed objects."""
    object1_speed, object2_speed = abs(object1["speed"]), abs(object2["speed"])
    active, passive = (
        (object1, object2)
        if object1_speed > object2_speed
        # Ensure consistent ordering for objects with the same speed by using
        # the only guaranteed-consistent attribute
        or (
            object1_speed == object2_speed
            and str(object1["index"]) < str(object2["index"])
        )
        else (object2, object1)
    )
    active_aspect_rule = (
        config.aspect_rules[active["index"]]
        if active["index"] in config.aspect_rules
        else config.default_aspect_rule
    )
    passive_aspect_rule = (
        config.aspect_rules[passive["index"]]
        if passive["index"] in config.aspect_rules
        else config.default_aspect_rule
    )
    # Intersect the aspects each object can make with the ones allowed by the config
    valid_aspects = [
        aspect
        for aspect in (
            set(active_aspect_rule["initiate"]) & set(passive_aspect_rule["receive"])
        )
        if aspect in config.aspects
    ]
    # Ordering by major first favors more significant aspects if multiple are found
    check_aspects = [
        aspect for aspect in valid_aspects if aspect in calc.MAJOR_ASPECTS
    ] + [aspect for aspect in valid_aspects if aspect not in calc.MAJOR_ASPECTS]
    # Get the orbs & actual distance
    active_orbs = (
        config.orbs[active["index"]]
        if active["index"] in config.orbs
        else config.planet_orbs
    )
    passive_orbs = (
        config.orbs[passive["index"]]
        if passive["index"] in config.orbs
        else config.planet_orbs
    )
    default_orb = config.default_orb
    distance = swe.difdeg2n(passive["lon"], active["lon"])
    separation = abs(distance)
    # Perform the actual aspect search
    for aspect in check_aspects:
        active_orb = active_orbs[aspect] if aspect in active_orbs else default_orb
        passive_orb = passive_orbs[aspect] if aspect in passive_orbs else default_orb
        orb = (
            ((active_orb + passive_orb) / 2)
            if config.orb_calculation == calc.MEAN
            else max(active_orb, passive_orb)
        )
        if aspect - orb <= separation <= aspect + orb:
            aspect_orb = separation - aspect
            exact_lon = swe.degnorm(
                passive["lon"] + (aspect if distance < 0 else -aspect)
            )
            associate = position.sign(exact_lon) == position.sign(active)
            exact = (
                exact_lon - config.exact_orb
                <= active["lon"]
                <= exact_lon + config.exact_orb
            )
            applicative = not exact and (
                (aspect_orb < 0 if distance < 0 else aspect_orb > 0)
                or active["speed"] < -calc.STATION_SPEED
            )
            return {
                "active": active["index"],
                "passive": passive["index"],
                "aspect": aspect,
                "orb": orb,
                "distance": distance,
                "difference": aspect_orb,
                "movement": calc.EXACT
                if exact
                else calc.APPLICATIVE
                if applicative
                else calc.SEPARATIVE,
                "condition": calc.ASSOCIATE if associate else calc.DISSOCIATE,
            }
    return {}


def for_object(
    object: dict,
    objects: dict,
    exclude_same: bool = True,
    config: Config = DEFAULTS,
) -> dict:
    """Returns all chart objects aspecting the passed chart object. If two
    separate sets of objects are being compared (eg. synastry) then
    exclude_self can be set to False to find aspects between the same
    object in both charts."""
    aspects = {}
    for index, check_object in objects.items():
        if exclude_same and index == object["index"]:
            continue
        aspect = between(object, check_object, config=config)
        if aspect:
            aspects[check_object["index"]] = aspect
    return aspects


def all(objects: dict, exclude_same: bool = True, config: Config = DEFAULTS) -> dict:
    """Returns all aspects between the passed chart objects."""
    aspects = {}
    check_objects = objects.copy()
    for index, object in objects.items():
        object_aspects = for_object(object, check_objects, exclude_same, config=config)
        for aspected_index, object_aspect in object_aspects.items():
            aspects.setdefault(index, {})[aspected_index] = object_aspect
            aspects.setdefault(aspected_index, {})[index] = object_aspect
        check_objects.pop(index)
    return aspects


def by_type(
    objects: dict,
    exclude_same: bool = True,
    config: Config = DEFAULTS,
) -> dict:
    """Returns all aspects between the passed chart objects keyed by
    aspect type."""
    aspects = {}
    check_objects = objects.copy()
    for index, object in objects.items():
        object_aspects = for_object(object, check_objects, exclude_same, config=config)
        for object_aspect in object_aspects.values():
            aspects.setdefault(object_aspect["aspect"], []).append(object_aspect)
        check_objects.pop(index)
    return aspects


def synastry(
    objects1: dict,
    objects2: dict,
    exclude_same: bool = False,
    config: Config = DEFAULTS,
) -> dict:
    """Returns all aspects between the two sets of passed chart objects."""
    aspects = {}
    for index, object in objects1.items():
        object_aspects = for_object(object, objects2, exclude_same, config=config)
        if object_aspects:
            aspects[index] = object_aspects
    return aspects
