"""
This file is part of immanuel - (C) The Rift Lab
Author: Robert Davies (robert@theriftlab.com)


Extracts the chart-shape pattern from a dict of chart objects provided
by the sweph or ephemeris modules, and the aspect patterns from a dict
of aspects provided by the aspect module.

For the aspect pattern search, each vertex's required aspects for each aspect
pattern is defined in the _ASPECT_PATTERNS dict. Its slightly cryptic formatting
was generated by first creating a list comprehension of the differences between
relative vertex longitudes for each step of each pattern - for example
(0, 90, 180) for T-square - and then hard-coding those values to avoid
recalculating them on the fly every time. For example, T-square requires:
{ (0, 1): calc.SQUARE, (0, 2): calc.OPPOSITION, (1, 2): calc.SQUARE }
but this format is difficult to compare to our existing aspects, so they are
defined as below to be more search-code-friendly.

"""

from collections import defaultdict

import swisseph as swe

from immanuel.const import calc
from immanuel.settings import DEFAULTS, Config

_ASPECT_PATTERNS = {
    calc.T_SQUARE: ((calc.SQUARE,), (calc.OPPOSITION, calc.SQUARE)),
    calc.GRAND_TRINE: ((calc.TRINE,), (calc.TRINE, calc.TRINE)),
    calc.YOD: ((calc.SEXTILE,), (calc.QUINCUNX, calc.QUINCUNX)),
    calc.GRAND_CROSS: (
        (calc.SQUARE,),
        (calc.OPPOSITION, calc.SQUARE),
        (calc.SQUARE, calc.OPPOSITION, calc.SQUARE),
    ),
    calc.KITE: (
        (calc.TRINE,),
        (calc.OPPOSITION, calc.SEXTILE),
        (calc.TRINE, calc.TRINE, calc.SEXTILE),
    ),
    calc.MYSTIC_RECTANGLE: (
        (calc.SEXTILE,),
        (calc.OPPOSITION, calc.TRINE),
        (calc.TRINE, calc.OPPOSITION, calc.SEXTILE),
    ),
    calc.CRADLE: (
        (calc.SEXTILE,),
        (calc.TRINE, calc.SEXTILE),
        (calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
    ),
    calc.GRAND_SEXTILE: (
        (calc.SEXTILE,),
        (calc.TRINE, calc.SEXTILE),
        (calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
        (calc.TRINE, calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
        (calc.SEXTILE, calc.TRINE, calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
    ),
    calc.GRAND_QUINTILE: (
        (calc.QUINTILE,),
        (calc.BIQUINTILE, calc.QUINTILE),
        (calc.BIQUINTILE, calc.BIQUINTILE, calc.QUINTILE),
        (calc.QUINTILE, calc.BIQUINTILE, calc.BIQUINTILE, calc.QUINTILE),
    ),
}


def aspect_patterns(aspects: dict) -> dict:
    """Iterates through the aspect patterns and searches the passed aspects for
    matches. Conjunctions are taken into account to avoid multiple hits of the
    same pattern with conjunct objects on one or more vertices."""
    # First we group conjunct objects into clusters, so that each cluster can
    # act as a single vertex & prevent the search from triggering multiple hits
    clusters = {}
    for index, aspect_list in aspects.items():
        conjunct = {index} | {
            aspected
            for aspected, aspect_data in aspect_list.items()
            if aspect_data["aspect"] == calc.CONJUNCTION
        }
        cluster = frozenset().union(
            conjunct, *(clusters[i] for i in conjunct if i in clusters)
        )
        clusters.update(dict.fromkeys(cluster, cluster))
    # Synastry aspects are not guaranteed bidirectional, so objects in one chart
    # might end up aspecting objects in the other without receiving an aspect of
    # its own. Here we ensure the aspects work in both directions, ready for the
    # aspect graph construction.
    for aspect_list in aspects.values():
        for aspected in aspect_list:
            clusters.setdefault(aspected, frozenset({aspected}))
    # Now build a graph keyed by cluster and aspect, with sets of aspected
    # clusters as values
    aspect_graph = defaultdict(set)
    for index, aspect_list in aspects.items():
        for aspected, aspect_data in aspect_list.items():
            aspect_graph[clusters[index], aspect_data["aspect"]].add(clusters[aspected])
    # Initial match checks begin with everything that has aspects
    initial_matches = list({(cluster,) for cluster in clusters.values()})
    candidates = {}
    for aspect_pattern, vertex_aspects in _ASPECT_PATTERNS.items():
        matches = initial_matches.copy()
        for required_aspects in vertex_aspects:
            inline_matches = []
            for match in matches:
                candidate_sets = []
                # Match our cluster / required aspect pair with actual
                # cluster / aspect pairs - defaultdict(set) ensures we
                # will always have something to append
                for cluster, aspect in zip(match, required_aspects):
                    candidate_sets.append(aspect_graph[cluster, aspect])
                # Collapse the candidate sets into unique, valid candidates
                valid_candidates = set.intersection(*candidate_sets)
                for candidate in valid_candidates:
                    inline_matches.append(match + (candidate,))
            matches = inline_matches
        # Ensure unique cluster combos per pattern
        if matches:
            candidates[aspect_pattern] = {frozenset(match): match for match in matches}
    # By now "candidates" will contain valid aspect patterns - our next step
    # is to prevent multiple hits stemming from nested patterns sitting within
    # larger ones, even if they're technically valid
    patterns = {}
    vertex_sets = [
        vertices for candidate in candidates.values() for vertices in candidate
    ]
    for aspect_pattern, candidate in candidates.items():
        for vertices, match in candidate.items():
            # Only register this pattern if it isn't a subset of a larger one
            if not any(vertices < competing for competing in vertex_sets):
                patterns.setdefault(aspect_pattern, []).append(
                    tuple(tuple(vertex_indices) for vertex_indices in match)
                )
    return patterns


def chart_shape(objects: dict, config: Config = DEFAULTS) -> int:
    """Returns which of the predetermined shapes the passed
    chart objects form."""

    # Wrapping "next n steps in list" helper function
    def wrapped(data: list, steps: int = 1) -> zip:
        return zip(*[data[i:] + data[:i] for i in range(0, steps + 1)])

    # Filter & sort objects by longitude
    longitudes = sorted(
        [v["lon"] for k, v in objects.items() if k in config.chart_shape_objects]
    )
    # Default to splash if the chart is unfeasibly small
    if len(longitudes) <= 1:
        return calc.SPLASH
    # Calculate the gaps between consecutive longitudes
    gaps = [swe.difdegn(next, lon) for lon, next in wrapped(longitudes)]
    max_gap = max(gaps)
    chart_shape_orb = config.chart_shape_orb
    # All planets within 120º can only be a bundle
    if max_gap >= 240 - chart_shape_orb:
        return calc.BUNDLE
    # For a bucket to form, the handle planet(s) must be at least 90º from the
    # edges of the main cluster. We allow up to two planets (conjunct within
    # chart_shape_orb) to form the handle - any more and this will be
    # classified as a seesaw.
    for gap, next, second_next in wrapped(gaps, steps=2):
        if gap >= 90 - chart_shape_orb and (
            next >= 90 - chart_shape_orb
            or (next <= chart_shape_orb and second_next >= 90 - chart_shape_orb)
        ):
            return calc.BUCKET
    # All planets being within 180º with no bucket handle means a bowl
    if max_gap >= 180 - chart_shape_orb:
        return calc.BOWL
    # All planets being within 240º with no bucket handle means a locomotive
    if max_gap >= 120 - chart_shape_orb:
        return calc.LOCOMOTIVE
    # Only two gaps of at least 60º mean a seesaw
    if sum(gap >= 60 - chart_shape_orb for gap in gaps) == 2:
        return calc.SEESAW
    # Three gaps of at least 30º mean a splay
    if sum(gap >= 30 - chart_shape_orb for gap in gaps) == 3:
        return calc.SPLAY
    # Default to no particular pattern
    return calc.SPLASH
