"""
This file is part of immanuel - (C) The Rift Lab
Author: Robert Davies (robert@theriftlab.com)


Extracts the chart-shape pattern from a dict of chart objects provided
by the sweph or ephemeris modules, and the aspect patterns from a dict
of aspects provided by the aspect module.

"""

from collections import defaultdict

import swisseph as swe

from immanuel.const import calc
from immanuel.settings import DEFAULTS, Config

""" Defines the vertex aspects required of each aspect pattern. This slightly
cryptic formatting was generated by first creating a list comprehension of the
differences between relative vertex longitudes for each pattern - for example,
(0, 90, 180) for T-Square - and then hard-coding those values to avoid
recalculating them on the fly for every iteration. """
_ASPECT_PATTERNS = {
    calc.T_SQUARE: ((calc.SQUARE,), (calc.OPPOSITION, calc.SQUARE)),
    calc.GRAND_TRINE: ((calc.TRINE,), (calc.TRINE, calc.TRINE)),
    calc.YOD: ((calc.SEXTILE,), (calc.QUINCUNX, calc.QUINCUNX)),
    calc.GRAND_CROSS: (
        (calc.SQUARE,),
        (calc.OPPOSITION, calc.SQUARE),
        (calc.SQUARE, calc.OPPOSITION, calc.SQUARE),
    ),
    calc.KITE: (
        (calc.TRINE,),
        (calc.OPPOSITION, calc.SEXTILE),
        (calc.TRINE, calc.TRINE, calc.SEXTILE),
    ),
    calc.MYSTIC_RECTANGLE: (
        (calc.SEXTILE,),
        (calc.OPPOSITION, calc.TRINE),
        (calc.TRINE, calc.OPPOSITION, calc.SEXTILE),
    ),
    calc.CRADLE: (
        (calc.SEXTILE,),
        (calc.TRINE, calc.SEXTILE),
        (calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
    ),
    calc.GRAND_SEXTILE: (
        (calc.SEXTILE,),
        (calc.TRINE, calc.SEXTILE),
        (calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
        (calc.TRINE, calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
        (calc.SEXTILE, calc.TRINE, calc.OPPOSITION, calc.TRINE, calc.SEXTILE),
    ),
    calc.GRAND_QUINTILE: (
        (calc.QUINTILE,),
        (calc.BIQUINTILE, calc.QUINTILE),
        (calc.BIQUINTILE, calc.BIQUINTILE, calc.QUINTILE),
        (calc.QUINTILE, calc.BIQUINTILE, calc.BIQUINTILE, calc.QUINTILE),
    ),
}


def aspect_patterns(aspects: dict) -> dict:
    """Iterates through the aspect patterns and searches the passed aspects for
    matches. The passed aspect dict is reshaped into a simple graph to make
    quick lookups possible without recursion."""
    # Build a graph keyed by chart object and aspect,
    # with sets of aspected chart objects as values
    aspect_graph = defaultdict(set)
    for aspecting_index, aspect_list in aspects.items():
        for aspected_index, aspect_data in aspect_list.items():
            aspect_graph[aspecting_index, aspect_data["aspect"]].add(aspected_index)
    # Initial match checks begin with every chart object with an aspect
    initial_matches = [(index,) for index in aspects]
    patterns = {}
    for pattern_type, vertex_aspects in _ASPECT_PATTERNS.items():
        matches = initial_matches.copy()
        for required_aspects in vertex_aspects:
            # This could be squashed into a single comprehension but
            # my brain is too fried to comprehend such a comprehension
            inline_matches = []
            for match in matches:
                candidate_sets = []
                # Match our index / required aspect pair with actual
                # index / aspect pairs - defaultdict(set) ensures we
                # will always have something to append
                for index, aspect in zip(match, required_aspects):
                    candidate_sets.append(aspect_graph[index, aspect])
                # Collapse the candidate sets into valid only
                valid_candidates = set.intersection(*candidate_sets)
                for candidate in valid_candidates:
                    inline_matches.append(match + (candidate,))
            matches = inline_matches
        # Ensure unique chart-object combos per pattern
        if matches:
            patterns[pattern_type] = list({frozenset(m): m for m in matches}.values())
    return patterns


def chart_shape(objects: dict, config: Config = DEFAULTS) -> int:
    """Returns which of the predetermined shapes the passed
    chart objects form."""
    # Filter & sort objects by longitude
    longitudes = sorted(
        [v["lon"] for k, v in objects.items() if k in config.chart_shape_objects]
    )
    # Default to splash if the chart is unfeasibly small
    if len(longitudes) <= 1:
        return calc.SPLASH
    # Calculate the gaps between consecutive longitudes
    gaps = [swe.difdegn(next, lon) for lon, next in _wrapped(longitudes)]
    max_gap = max(gaps)
    chart_shape_orb = config.chart_shape_orb
    # All planets within 120º can only be a bundle
    if max_gap >= 240 - chart_shape_orb:
        return calc.BUNDLE
    # For a bucket to form, the handle planet(s) must be at least 90º from the
    # edges of the main cluster. We allow up to two planets (conjunct within
    # chart_shape_orb) to form the handle - any more and this will be
    # classified as a seesaw.
    for gap, next, second_next in _wrapped(gaps, steps=2):
        if gap >= 90 - chart_shape_orb and (
            next >= 90 - chart_shape_orb
            or (next <= chart_shape_orb and second_next >= 90 - chart_shape_orb)
        ):
            return calc.BUCKET
    # All planets being within 180º with no bucket handle means a bowl
    if max_gap >= 180 - chart_shape_orb:
        return calc.BOWL
    # All planets being within 240º with no bucket handle means a locomotive
    if max_gap >= 120 - chart_shape_orb:
        return calc.LOCOMOTIVE
    # Only two gaps of at least 60º mean a seesaw
    if sum(gap >= 60 - chart_shape_orb for gap in gaps) == 2:
        return calc.SEESAW
    # Three gaps of at least 30º mean a splay
    if sum(gap >= 30 - chart_shape_orb for gap in gaps) == 3:
        return calc.SPLAY
    # Default to no particular pattern
    return calc.SPLASH


def _wrapped(data: list, steps: int = 1) -> zip:
    """Returns a zip with each entry containing the current and next "steps"
    entries of the passed list, wrapping back to the start if the indices fall
    off the end."""
    return zip(*[data[i:] + data[:i] for i in range(0, steps + 1)])
