[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "immanuel"
version = "1.6.0"
description = "Quickly produce both human-readable and JSON-formatted astrology chart data based on the Swiss Ephemeris and astro.com."
authors = [
  { name = "Robert Davies", email = "robert@theriftlab.com" },
]
license = "AGPL-3.0-or-later"
license-files = ["LICENSE.md"]
readme = "README.md"
keywords = ["astrology", "api", "pyswisseph", "pysweph", "swisseph", "swiss ephemeris", "astro.com", "astro gold"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10"
dependencies = [
    "pysweph>=2.10.3.3",
    "python-dateutil>=2.8.2",
    "scipy>=1.10",
    "timezonefinder~=5.2",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-lazy-fixtures",
    "scipy-stubs",
]

[project.urls]
"Homepage" = "https://github.com/theriftlab/immanuel-python"
"Documentation" = "https://github.com/theriftlab/immanuel-python/blob/master/docs/1-overview.md"
"Bug Tracker" = "https://github.com/theriftlab/immanuel-python/issues"

[tool.setuptools.packages.find]
include = ["immanuel*"]

[tool.setuptools]
include-package-data = true

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
testpaths = ["tests"]
