"""
    This file is part of immanuel - (C) The Rift Lab
    Author: Robert Davies (robert@theriftlab.com)


    Defines indices for the chart classes to define what data should be
    included for output.

"""


NATAL_DATE = 0
COORDINATES = 1
PARTNER_DATE = 2
PARTNER_COORDINATES = 3
SOLAR_RETURN_YEAR = 4
SOLAR_RETURN_DATE = 5
PROGRESSION_DATE = 6
PROGRESSED_DATE = 7
PROGRESSION_METHOD = 8
HOUSE_SYSTEM = 9
SHAPE = 10
PARTNER_SHAPE = 11
DIURNAL = 12
PARTNER_DIURNAL = 13
MOON_PHASE = 14
PARTNER_MOON_PHASE = 15
OBJECTS = 16
PARTNER_OBJECTS = 17
ASPECTS = 18
PARTNER_ASPECTS = 19
HOUSES = 20
PARTNER_HOUSES = 21
WEIGHTINGS = 22
PARTNER_WEIGHTINGS = 23
